# 리스트와 어레이

**기본 설정**

Numpy 라이브러리를 별칭 np로 불러온다.

In [1]:
import numpy as np

## 리스트

리스트는 여러 개의 값들을 모아놓은 `list` 클래스의 객체다. 

In [2]:
int_list = [2, 3, 7, 11]
float_list = [3.14, 2.17, 7.0, -0.856, 20.8]
str_list = ['foo', 'bar', 'baz']

리스트의 자료형은 항목의 자료형과 무관하다.

In [3]:
type(int_list)

list

In [4]:
type(float_list)

list

In [5]:
type(str_list)

list

**중첩 리스트**

리스트의 항목으로 리스트를 사용할 수도 있다.

In [74]:
list_2d = [[1, 2, 3, 4], [5, 6, 7, 8]]
list_2d

[[1, 2, 3, 4], [5, 6, 7, 8]]

리스트의 항목으로 사용된 리스트들의 길이다 다를 수도 있다.

In [75]:
list_ragged = [[1, 2, 3, 4], [5, 6, 7], [8, 9]]
list_ragged

[[1, 2, 3, 4], [5, 6, 7], [8, 9]]

### 리스트 인덱싱

인덱스를 이용하여 지정된 위치의 항목을 추출할 수 있다.

In [6]:
int_list[0]

2

In [7]:
float_list[-1]

20.8

In [8]:
str_list[1]

'bar'

2중으로 중첩된 리스트를 대상으로도 인덱싱이 반복적으로 적용된다.

In [76]:
list_2d[0]

[1, 2, 3, 4]

In [77]:
list_2d[0][2]

3

In [78]:
list_ragged[2][1]

9

인덱싱을 이용하여 리스트 항목을 다른 항목으로 변경할 수 있다.

In [9]:
int_list[0] = 1
int_list

[1, 3, 7, 11]

In [10]:
float_list[-1] = 5
float_list

[3.14, 2.17, 7.0, -0.856, 5]

In [11]:
str_list[1] = 'peekaboo'
str_list

['foo', 'peekaboo', 'baz']

In [80]:
list_ragged[2][1] = 11
list_ragged

[[1, 2, 3, 4], [5, 6, 7], [8, 11]]

### 리스트 슬라이싱

슬라이싱을 이용하여 동시에 여러 개의 값을 추출할 수 있다.
아래 코드는 1번부터 4번 인덱스의 값으로 이루어진 리스트를 생성한다.

In [12]:
seq = [7, 2, 3, 7, 5, 6, 0, 1]
sub_seq = seq[1:5]

sub_seq

[2, 3, 7, 5]

<div align="center"><img src="https://github.com/codingalzi/pydata/blob/master/notebooks/images/list_slicing10.png?raw=1" style="width:420px;"></div>

위 그림에서 볼 수 있듯이 슬라이싱은 기존에 주어진 리스트를 수정하지 않으면서
구간 정보를 활용하여 새로운 리스트를 생성한다.

In [13]:
seq

[7, 2, 3, 7, 5, 6, 0, 1]

슬라이싱 구간의 시작과 끝을 지정하는 값을 필요에 따라 선택적으로 생략할 수도 있다.
생략된 값은 각각 리스트의 처음과 끝을 가리키는 값으로 처리된다.
아래 코드는 0번 인덱스부터 4번 인덱스까지의 구간을 대상으로 한다.

In [14]:
seq[:5]

[7, 2, 3, 7, 5]

아래 코드는 3번 인덱스부터 리스트 오른편 끝가지를 대상으로 한다.

In [15]:
seq[3:]

[7, 5, 6, 0, 1]

음수 인덱스는 리스트 오른편 부터 -1, -2, -3, 등으로 왼편으로 이동하면서 지정된다.
아래 코드는 끝에서 4번째부터 마지막까지 구간을 대상으로 한다.

In [16]:
seq[-4:]

[5, 6, 0, 1]

아래 코드는 끝에서 6번째부터 끝에서 두번째 이전, 즉, 끝에서 세번째까지 슬라이싱한다.

In [17]:
seq[-6:-2]

[3, 7, 5, 6]

구간의 처음과 끝이 모두 생략되면 리스트 전체를 대상으로 한다.
아래 코드는 리스트 전체를 대상으로 하지만 2 스텝씩 건너 뛰며 항목을 슬라이싱한다.
즉, 0, 2, 4, ... 등의 인덱스를 대상으로 한다.

In [18]:
seq[::2]

[7, 3, 5, 0]

### 리스트 연산

두 개의 리스트를 이어붙이거나 하나의 리스트를 복제해서 이어붙이는 기능을 지원한다.
아래 코드는 두 개의 리스트를 이어붙여서 새로운 리스틀 생성하는 방법을 보여준다.

In [19]:
float_list + str_list

[3.14, 2.17, 7.0, -0.856, 5, 'foo', 'peekaboo', 'baz']

아래 코든 하나의 리스트를 지정된 정수만큼 복제해서 이어붙인다.

In [20]:
int_list * 3

[1, 3, 7, 11, 1, 3, 7, 11, 1, 3, 7, 11]

### `range` 객체

`range()` 함수는 규칙성을 가진 정수들의 모음을 반환한다.
반환값은 `range` 객체이며 리스트와 유사하게 작동한다.
예를 들어, 0부터 9까지의 정수들로 이루어진 `range` 객체를 다음과 같이 생성한다.

In [21]:
range(10)

range(0, 10)

`range(10)`은 `range(0, 10)`과 동일하다.
이때 첫째 인자 0은 구간의 시작을, 둘째 인자는 10은 구간의 끝보다 하나 큰 값을 가리킨다.
반환된 값의 자료형은 `range` 이다.

In [22]:
type(range(10))

range

리스트로 형변환을 하면 보다 명확하게 확인된다.

In [23]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

슬라이싱에서 처럼 스텝을 사용할 수 있다.
예를 들어, 0에서 19까지의 정수중에서 짝수만으로 이루어진 `range` 객체는 다음과 같이 
스텝(step) 크기 2를 셋째 인자로 지정하여 생성한다.

In [24]:
list(range(0, 20, 2))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

## 넘파이 어레이

**넘파이**<font size='2'>numpy</font>는 NUMerical PYthon의 줄임말이며, 
파이썬 데이터 과학에서 가장 중요한 도구를 제공하는 라이브러리이다.
넘파이가 제공하는 가장 중요한 요소는 아래 두 가지이다.

* 다차원 어레이(배열)
* 메모리 효율적이며 빠른 어레이 연산

넘파이의 기능을 잘 이해한다면 이어서 다룰 **판다스**<font size='2'>pandas</font> 라이브러리가 지원하는
데이터프레임<font size='2'>Dataframe</font> 자료형의 기능 또한 쉽게 이해할 수 있다. 

### 다차원 어레이

넘파이 어레이는 리스트와는 달리 포함된 모양, 항목의 자료형 등에 대한 자료형 정보도 포함한다.
모양에 따라 차원이 결정되며, 모든 항목은 동일한 자료형을 갖는다.
가장 많이 활용되는 어레이의 차원은 다음과 같다.

**1차원 어레이**

리스트와 유사한 모양을 가지며, 리스트 등에 `np.array()` 함수를 적용하여 생성할 수 있다.
1차원 어레이는 **벡터**<font size='2'>vector</font>로도 불리며, 
한 개의 **축**<font size='2'>axis</font>을 갖는다.

* 리스트 활용

In [25]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

**`ndarray` 자료형**

넘파이 어레이 자체의 자료형은 `ndarray`이다. 

In [26]:
type(arr1)

numpy.ndarray

**2차원 어레이**

동일한 길이의 리스트를 항목으로 갖는 중첩 리스트를 
2차원 어레이로 변환할 수 있다.
따라서 2차원 어레이는 어레이의 모든 항목은
동일한 크기의 1차원 어레이이다.
2차원 어레이는 **행렬**<font size='2'>matrix</font>로도 불리며, 
**행**<font size='2'>row</font>과 **열**<font size='2'>column</font> 
두 개의 축을 갖는다.

In [27]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

`list_ragged`처럼 리스트의 항목이 서로 길이가 다른 리스트인 경우엔 어레이로의 변환이 허용되지 않는다.
즉, 2차원 어레이는 직사각형 형식의 행렬이어야 한다.

In [81]:
list_ragged

[[1, 2, 3, 4], [5, 6, 7], [8, 11]]

In [82]:
np.array(list_ragged)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

**`shape`** 속성

어레이 객체의 `shape` 속성은 생성된 어레이의 모양을 저장한다.
예를 들어 위 2차원 어레이의 모양은 행과 열의 개수로 구성된 튜플 `(2, 4)`이다.

In [28]:
arr2.shape

(2, 4)

1차원 어레이, 즉 벡터의 모양은 벡터에 포함된 항목의 개수로 구성된
길이가 1인 튜플로 표현된다.

In [29]:
arr1.shape

(5,)

**`ndim` 속성**

차원은 `ndim` 속성에 저장되며, `shape`에 저정된 튜플의 길이와 동일하다.

In [30]:
arr2.ndim

2

1차원 어레이의 차원은 1이다.

In [31]:
arr1.ndim

1

**고차원 어레이**

3차원, 4차원 등의 고차원 어레이도 다룰 수 있지만 여기서는 사용하지 않는다.

### `np.arange()` 함수

`np.arange()` 함수는 `range()` 함수와 유사하게 작동하지만 반환값은 항상 넘파이 어레이다.

In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`range()` 함수와 유사하게 작동하며 부동소수점 스텝도 지원한다.

In [33]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### `dtype` 종류

넘파이 어레이의 `dtype` 속성은 어레이 항목의 자료형을 담고 있으며, 파이썬 표준 라이브러리에서 제공하는 
`int`, `float`, `str` 등을 보다 세분화시킨 자료형을 제공한다.

**`float` 자료형**

In [35]:
arr1 = np.array([1.0, 2, 3.2])

arr1.dtype

dtype('float64')

In [36]:
arr1 = np.array([1.0, 2, 3.2]).astype('float32')

arr1.dtype

dtype('float32')

**`int` 자료형**

In [37]:
arr2 = np.array([1, 2, 3])

arr2.dtype

dtype('int64')

In [38]:
arr2 = np.array([1, 2, 3]).astype('int32')

arr2.dtype

dtype('int32')

**문자열 자료형**

문자열은 기본적으로 유니코드로 처리되며 크기는 최장 길이의 문자열에 맞춰 결정된다.

In [39]:
np.array(['python', 'data']).dtype

dtype('<U6')

In [40]:
numeric_strings = np.array(['1.25', '-9.6', '42'])
numeric_strings.dtype

dtype('<U4')

**`bool` 자료형**

In [41]:
np.array([True, False]).dtype

dtype('bool')

### 어레이 연산

넘파이 어레이 연산은 기본적으로 항목별로 이루어진다. 
즉, 지정된 연산을 동일한 위치의 항목끼리 실행하여 새로운, 동일한 모양의 어레이를 생성한다.

**1차원 어레이 연산**

숫자와의 연산은 모든 항목에 동일한 값을 사용한다.

In [42]:
arr1 + arr2

array([2.        , 4.        , 6.20000005])

In [43]:
arr1 - 2

array([-1. ,  0. ,  1.2], dtype=float32)

In [44]:
arr1 * arr2

array([1.        , 4.        , 9.60000014])

In [45]:
arr1 / 2.3

array([0.43478262, 0.86956525, 1.3913044 ], dtype=float32)

**2차원 어레이 연산**

숫자와의 연산은 모든 항목에 동일한 값을 사용한다.

In [46]:
arr3= np.array([[1., 2., 3.], [4., 5., 6.]])
arr3

array([[1., 2., 3.],
       [4., 5., 6.]])

In [47]:
arr4 = np.array([[3., 2., 1.], [4., 2., 12.]])
arr4

array([[ 3.,  2.,  1.],
       [ 4.,  2., 12.]])

In [48]:
arr3 + arr4

array([[ 4.,  4.,  4.],
       [ 8.,  7., 18.]])

In [49]:
arr3 - arr4

array([[-2.,  0.,  2.],
       [ 0.,  3., -6.]])

In [50]:
arr3 * arr4

array([[ 3.,  4.,  3.],
       [16., 10., 72.]])

In [51]:
arr3 / arr4

array([[0.33333333, 1.        , 3.        ],
       [1.        , 2.5       , 0.5       ]])

In [52]:
arr3 + 2.4

array([[3.4, 4.4, 5.4],
       [6.4, 7.4, 8.4]])

In [54]:
3.78 - arr3

array([[ 2.78,  1.78,  0.78],
       [-0.22, -1.22, -2.22]])

**비교 연산**

In [55]:
arr4 > arr3

array([[ True, False, False],
       [False, False,  True]])

In [56]:
arr4 <= arr3

array([[False,  True,  True],
       [ True,  True, False]])

In [57]:
1.2 < arr3

array([[False,  True,  True],
       [ True,  True,  True]])

In [58]:
1.2 >= arr4

array([[False, False,  True],
       [False, False, False]])

In [59]:
arr3 == arr3

array([[ True,  True,  True],
       [ True,  True,  True]])

In [60]:
arr3 != arr4

array([[ True, False,  True],
       [False,  True,  True]])

**논리 연산**

사용 가능한 논리 연산은 아래 세 가지이다.

* `~`: 부정(not) 연산자
* `&`: 논리곱(and) 연산자
* `|`: 논리합(or) 연산자

In [61]:
~(arr3 == arr3)

array([[False, False, False],
       [False, False, False]])

In [62]:
(arr3 == arr3) & (arr4 == arr4)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [63]:
~(arr3 == arr3) | (arr4 == arr4)

array([[ True,  True,  True],
       [ True,  True,  True]])

### 어레이 모양 변형

주어진 어레이의 항목을 그대로 유지하면서 모양만 변형시키는 방식과
활용법을 소개한다.

**`reshape()` 메서드**

`reshape()` 메서드를 활용하여 주어진 어레이의 모양을 원하는 대로 변형한다.
단, 항목의 수가 변하지 않도록 모양을 지정해야 한다.
예를 들어, 길이가 8인 1차원 어레이가 다음과 같다.

In [64]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

이제 (4, 2) 모양의 2차원 어레이로 모양을 변형할 수 있다.

In [65]:
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

항목의 수만 같으면 임의의 차원의 어레이를 임의의 차원의 어레이로 변형시킬 수 있다.

In [66]:
arr.reshape((4, 2)).reshape((2, 2, 2))

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

**`-1`의 역할**

어레의 모양을 지정할 때 튜플의 특정 위치에 -1을 사용할 수 있다.
그러면 그 위치의 값은 튜플의 다른 항목의 정보를 이용하여 자동 결정된다.
예를 들어, 아래 코드에서 -1은 4를 의미한다. 
이유는 20개의 항목을 5개의 행으로 이루어진 2차원 어레이로 지정하려면 열은 4개 있어야 하기 때문이다.

In [67]:
arr = np.arange(20)
arr.reshape((5, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [68]:
arr.reshape((5, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

### 1차원 어레이 인덱싱, 슬라이싱

1차원 어레이이 대해서는 리스트의 경우와 거의 동일하다.

In [83]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

* 인덱싱: 리스트의 경우와 동일

In [84]:
arr[5]

5

* 슬라이싱: 구간 확인 기능은 리스트의 경우와 동일

In [85]:
arr[5:8]

array([5, 6, 7])

**뷰<font size='2'>view</font> 이해**

넘파이 어레이에 대해 슬라이싱을 실행하면 지정된 구간에 해당하는 어레이를 새로 생성하는 게 아니라
지정된 구간의 정보를 이용만 한다. 
이렇게 작동하는 기능이 **뷰**이다. 
즉, 어레이를 새로 생성하지 않고 기존 어레이를 적절하게 활용한다.
넘파이 어레이와 관련된 많은 기능이 뷰 기능을 이용한다.

In [87]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

슬라이스의 항목을 변경하면 `arr` 변수가 가리키는 어레이의 항목도 함께 달라진다.

In [88]:
arr_slice[1] = 3450
arr

array([   0,    1,    2,    3,    4,   12, 3450,   12,    8,    9])

**`copy()` 메서드**

원본을 그대로 유지하려면 `copy()` 메서드를 이용하여 사본을 만들어 활용할 것을 권장한다.

In [89]:
arr_slice2 = arr[5:8].copy()
arr_slice2

array([  12, 3450,   12])

`arr_slice2`를 변경해도 `arr`은 영향받지 않는다.

In [90]:
arr_slice2[1] = 12
arr_slice2

array([12, 12, 12])

In [91]:
arr

array([   0,    1,    2,    3,    4,   12, 3450,   12,    8,    9])

### 2차원 어레이 인덱싱, 슬라이싱

2차원 이상의 다차원 어레이는 보다 다양한 인덱싱, 슬라이싱 기능을 제공한다. 

In [92]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**인덱싱**

리스트의 인덱싱을 그대로 사용할 수 있다.

* 0번 인덱스 항목: 길이가 3인 1차원 어레이

In [93]:
arr2d[0]

array([1, 2, 3])

* 0번 인덱스의 2번 인덱스 항목: 리스트 인덱싱 방식
    - 0번 인덱스의 항목이 리스트이며, 그 리스트의 2번 인덱스 항목 확인

In [94]:
arr2d[0][2]

3

위 인덱싱을 2차원 어레이 인덱싱 방식으로 아래와 같이 쉽게 할 수 있다.

In [95]:
arr2d[0, 2]

3

**슬라이싱**

리스트 슬라이싱 방식을 동일하게 적용할 수 있다.

* 1번 인덱스 이전까지

In [96]:
arr2d[:1]

array([[1, 2, 3]])

* 2번 인덱스 이전까지

In [97]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

* 전체 항목 슬라이싱

In [98]:
arr2d[:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

행과 열을 함께 슬라이싱하려면 행과, 열에 대한 슬라이싱을 동시에 지정한다.

* 행 기준: 2번 행 이전까지
* 열 기준: 1번 열부터 끝까지

In [99]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

<div align="center" border="1px"><img src="https://raw.githubusercontent.com/codingalzi/datapy/master/jupyter-book/images/numpy149-1.png" style="width:350px;"></div>

인덱싱과 슬라이싱이 행과 열 각각에 대해 독립적으로 사용될 수 있다.

* 행 기준: 1번 행 인덱싱
* 열 기준: 2번 열 이전까지

In [100]:
arr2d[1, :2]

array([4, 5])

<div align="center" border="1px"><img src="https://raw.githubusercontent.com/codingalzi/datapy/master/jupyter-book/images/numpy149-4.png" style="width:350px;"></div>

**주의사항:** 

인덱싱을 사용하는 만큼 결과 어레이의 차원이 기존 어레이의 차원보다 1씩 줄어든다.
예를 들어, 아래 코드는 0번 축에 대해 인덱싱을 사용하였기에 0번 축이 사라지고 1번 축이 대신 0번축의 역할을 한다 라고 말할 수 있다.

In [101]:
arr2d[1, :2].shape

(2,)

동일한 항목을 사용하지만 인덱싱을 사용할 때와 아닐 때의 결과는 다른 모양의 어레이가 된다.

In [102]:
arr2d[1:2, :2]

array([[4, 5]])

모양은 사용되는 슬라이싱의 구간에 의존한다.

* 행 기준: 1번 행 하나만 사용
* 열 기준: 0번 열, 1번 열 사용.

따라서 결과는 (1, 2) 모양의 어레이다.

In [103]:
arr2d[1:2, :2].shape

(1, 2)

* 행 기준: 행 전체
* 열 기준: 2번 열 이전까지

In [104]:
arr2d[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

<div align="center" border="1px"><img src="https://raw.githubusercontent.com/codingalzi/datapy/master/jupyter-book/images/numpy149-3.png" style="width:350px;"></div>

In [105]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [106]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

**예제**

먼저 아래 그림 모양의 2차원 어레이를 생성한다.
길이가 36인 1차원 어레이를 (6, 6) 모양의 2차원 어레이로 항목을 재배열하기 위해
`reshape()` 함수를 사용한다.

In [107]:
arr = np.arange(36).reshape((6, 6)) + np.arange(0, 21, 4).reshape(6, 1)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

<div align="center" border="1px"><img src="https://raw.githubusercontent.com/codingalzi/datapy/master/jupyter-book/images/numpy-2darray.png" style="width:250px;"></div>

<p><div style="text-align: center">&lt;그림 출처: <a href="https://scipy-lectures.org/intro/numpy/array_object.html#indexing-and-slicing">Scipy Lecture Notes</a>&gt;</div></p>

위 그림에 색깔별로 표시된 어레이를 슬라이싱을 이용하여 구해보자.

* 빨강색 1차원 어레이

In [108]:
arr[0, 3:5]

array([3, 4])

* 파랑색 2차원 어레이

In [109]:
arr[:, 2:3]

array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52]])

열에 대해 슬라이싱 대신 인덱싱을 사용하면 1차원 어레이를 얻는다.

In [110]:
arr[:, 2]

array([ 2, 12, 22, 32, 42, 52])

* 보라색 2차원 어레이 (스텝 활용)

In [111]:
arr[2:5:2, 0::2]

array([[20, 22, 24],
       [40, 42, 44]])

* 초록색 2차원 어레이

In [112]:
arr[4:, 4:]

array([[44, 45],
       [54, 55]])

## 예제

**예제 1**

아래 모양의 2차원 어레이를 생성하라.

```python
array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])
```

어레이의 모양이 (6, 6)이기에 우선 `np.arange(36)`과 `reshape()` 메서드를 이용하여 아래 어레이를 생성한다.

In [69]:
arr_1 = np.arange(36).reshape(6, 6)
arr_1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

**예제 1**

이제 0행부터 차례대로 0, 4, 8, 12, 16, 20을 더해야 하기에 
언급된 값들을 항목으로 갖는 (6, 1) 모양의
어레이를 다음과 같이 생성한다.

In [70]:
arr_2 = np.arange(0, 21, 4).reshape(6, 1)
arr_2

array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16],
       [20]])

**예제 1**

이제 두 어레이를 더하면 원하는 2차원 어레이가 생성된다.

In [71]:
arr = arr_1 + arr_2
arr

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])